### ISSUE TITLE
How to use PageSpeed Insight on github

### ISSUE THREAD

**Issue by JayantGoel001** [lowlighter/lowlighter#1]
I was trying to use PageSpeed Insight on GitHub readme. I wrote the code and then added Google API in Secrets but still I am not able to retrieve the PageSpeed Insight and I don't know where to upload my GitHub URL or that link to analysis PageSpeed.

Kindly Help @lowlighter 
Thank You

**Comment by lowlighter** [comment]
Hello,
Thanks for reaching out !

You can add your website url from your GitHub profile by clicking ˋEdit profileˋ (you can also do it from settings too) :

![image](https://user-images.githubusercontent.com/22963968/103019908-d5fc2c00-4547-11eb-91a7-97d9ba5b6684.jpeg)

The twitter plugin also works the same way, it'll use the username you attached to your profile.

Have a nice day 👍

**Comment by JayantGoel001** [comment]
@lowlighter Ya Thanks Man, It Totally worked out.

**Comment by JayantGoel001** [comment]
@lowlighter Sorry to bother you again.
In commit activity per day, I think it only works in particular time zone 
Please Add In this "Indian Time Zone (IST)".

**Comment by lowlighter** [comment]
Glad it worked !

As for time zone, I'll add it to my todo-list, it's a good idea. 

I think current timezone is set on UTC+0 (London time). So it should have an offset of 5:30 hours from IST. 

I'll check it out after christmas 👍 

Thanks for using metrics !

**Comment by lowlighter** [comment]
I'll move the issue to [lowlighter/metrics](https://github.com/lowlighter/metrics)
